### ISSUE TITLE
plotProfile output plot bug: No break label shown in y-axis

### ISSUE THREAD

**Issue by ChevyXu** [deeptools/deepTools#844] opened 2019-06-28 10:20 UTC
### Issues have been viewed and no similar issue has been proposed
---
## Problem Description:
> When I get the matrix using `computeMatrix` command, I want to plot a plot using `plotProfile` command, a bug occurred in the plot, there is no y-axis label shown in the plot, just like the screenshot below:

![image](https://user-images.githubusercontent.com/26089675/60335547-cb072080-99d0-11e9-903b-4a5fe3b117fb.png)

**No break label were shown in plot**
My command: `plotProfile -m  My_heatmap.gz -out My_heatmap.pdf`

 ---
> Then I tried `plotHeatmap` command, the plot was shown below:

![image](https://user-images.githubusercontent.com/26089675/60335021-6c8d7280-99cf-11e9-8ddb-9622dc027749.png)

**Label is there**

---

#### Tips: Recently I reinstalled deeptools with conda, then I got this problem.

**Comment by dpryan79** [comment] 2019-07-01 19:02
FYI, you're not the only one running into this, we've started observing it locally. I think there's an issue with recent versions of matplotlib, but I haven't yet figured out exactly if that's the cause or not yet.

**Comment by dpryan79** [comment] 2019-09-03 10:30
This should finally be fixed in the develop branch and I'd like to push out a new release with it soon. Only matplotlib 3 is now supported, since I can't keep hacking around the differences in all of the different versions forever.

**Closed by dpryan79** 2019-09-03 10:30 UTC
Labels: bug, high Priority

**Comment by mkmwong** [comment] 2020-03-02 23:34
Pulled the newest version of deeptools and matplotlib version is 3.1.0 and also have the same problem. no y axis break is displayed while using plot profile, showed up on plot heatmap just like OP's.
