### ISSUE TITLE
plotFingerprint: No reads were found in 0 regions sampled

### ISSUE THREAD

**Issue by dzhaobio** [deeptools/deepTools#801] opened 2019-02-11 17:22 UTC
- [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

deeptools 3.1.3
Python 2.7.13

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

export QCDIR="QC_ChIPseq"
plotFingerprint -b mapped/*.bam -plot $QCDIR/deeptools_fingerprint.pdf --plotTitle "Fingerprints of different samples" --minMappingQuality 20 --outRawCounts $QCDIR/deeptools_fingerprint.tab --numberOfProcessors 4

$ samtools view -H mapped/INWT1.bam 
@HD	VN:1.6	SO:coordinate
@SQ	SN:chrI	LN:230218
@SQ	SN:chrII	LN:813184
@SQ	SN:chrIII	LN:316620
@SQ	SN:chrIV	LN:1531933
@SQ	SN:chrIX	LN:439888
@SQ	SN:chrM	LN:85779
@SQ	SN:chrV	LN:576874
@SQ	SN:chrVI	LN:270161
@SQ	SN:chrVII	LN:1090940
@SQ	SN:chrVIII	LN:562643
@SQ	SN:chrX	LN:745751
@SQ	SN:chrXI	LN:666816
@SQ	SN:chrXII	LN:1078177
@SQ	SN:chrXIII	LN:924431
@SQ	SN:chrXIV	LN:784333
@SQ	SN:chrXV	LN:1091291
@SQ	SN:chrXVI	LN:948066
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1188	CL:bwa mem -t 4 /home/bioinfo/genomes/igenomes/Saccharomyces_cerevisiae/UCSC/sacCer3/Sequence/BWAIndex/genome.fa INWT1/INWT1_R1.trimmed.fastq.gz INWT1/INWT1_R2.trimmed.fastq.gz

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

"No reads were found in 0 regions sampled. Check that the
min mapping quality is not overly high and that the 
chromosome names between bam files are consistant."

The bam files were generated using the same software and parameters, so they have the same chromosome names.  The min mapQ is 0. So I think the problem is that there is no region selected. 

Does the chromosome format affect the region selection process? 
I can run this analysis with human data (hg19 and hg38, chromosome name format: chr1, chr2 etc) without problem. But when I applied it to yeast data, I encountered the error. The yeast chromosome name is not following the format "chr+number" (refer to the sam header above), is that the reason for the error? Thank you!

**Comment by dpryan79** [comment] 2019-02-14 13:01
The chromosome naming format doesn't matter, but I wonder if you have a random non-yeast sample that got mixed in somehow. Can you run this on just 1 or 2 samples to see if that also yields the same error?

**Comment by dzhaobio** [comment] 2019-02-14 19:17
I tried several ways and here are the results in each trial.

1. I have 20 bam files. All of them are yeast samples. At the beginning, I included all the bam files, and I failed as mentioned above (I tried twice and both failed). The plotCoverage figure shows that the mean coverages for those samples are very large, from 160 to 400. These coverages are very high, compared to the human and mouse samples I worked on for which the mean coverage is usually around 1.

2. I tried to downsample all the samples (use 10M PE reads for each sample) and re-ran the analysis with all 20 samples. Finally I got the plotFingerprint figure. The plotCoverage figure shows that the mean coverages for those samples are very large, from 80 to 117.

3. I also tried to separate the samples into five groups (4 samples per group) without downsampling, and ran the analysis on each group separately. I also succeeded.

It shows the chromosome naming format is not the reason for the issue.

It seems it has something to do with the coverage. Is that possible?

**Comment by dpryan79** [comment] 2019-02-15 07:52
That's very odd, can you make one or two of them available to me for testing?

**Comment by dzhaobio** [comment] 2019-02-15 21:32
If you ran on one or two of them, probably you will succeed (refer to my trial 3). I failed when I ran on all 20 samples together without down-sampling. It's around 40GB for all the 20 files. I've put them on globus (https://www.globus.org/). I will send you an email about how to access the data. Thank you.

**Comment by dpryan79** [comment] 2019-02-17 11:57
The cause of this is that the size of the genome sent to each core decreases with the number of samples. That's usually not an issue, but with very small genomes (12MB in this case) it can quickly turn out that the size sent to each core is less than the bin length. I'll put in a check for this in version 3.2.0 and have it set the minimum size sent to each core to be the bin length.

**Comment by dpryan79** [comment] 2019-02-17 12:39
I have this fixed in the next release (I expect it will come out tomorrow).

**Closed** 2019-02-17 23:01 UTC
Labels: bug, enhancement
