### ISSUE TITLE
plotHeatmap (3.0.2): additional columns for clustered matrices?

### ISSUE THREAD

**Issue by thomasmanke** [deeptools/deepTools#714] opened 2018-05-28 13:43 UTC
plotHeatmap -m test.npz -o test.png --outFileNameMatrix test.txt --sortRegions keep

I have checked that the matrix seen by plotHeatmap is proper (test.txt) 

[test.txt](https://github.com/deeptools/deepTools/files/2045265/test.txt)
![test](https://user-images.githubusercontent.com/16337133/40617133-a65537de-628d-11e8-86cf-0d713118e83a.png)

In test.png; 
cluster 1 has 5 columns (as should be). 
cluster 2 is visualised with 6 columns (first white)

Just for reference, test.npz was generated using
computeMatrix scale-regions -R test.bed -S bw/CviKI_1.bw -o test.npz -m 100  -bs 20 --missingDataAsZero --averageTypeBins sum

**Comment by dpryan79** [comment] 2018-05-28 19:30
Looks like a weird rendering bug, where there's a bit too much padding on the bottom panel. This also happens if you don't use groups (then you get the extra ~half column padding on the whole thing). If you use k-means clustering to get 3 groups then only the bottom panel is affected, which confirms that this is what's happening. I'll see if I can track down the cause.

**Comment by dpryan79** [comment] 2018-05-28 19:52
This is due to `tickPlotAdj` in `heatmapper_utilities`, which results in 0.5 being subtracted from the position of ticks. Thus instead of the ticks being at 0 and 5 they're at -0.5 and 4.5. This half-column adjustment seems to have been done to make the ticks centered in the columns, though it ends up shifting a left-sided tick off the end. I'll create a fix for this in the next release.

**Comment by dpryan79** [comment] 2018-05-28 20:04
You'll notice that the profile and heatmap ticks don't line up, since the range of the profile will always be smaller than that from the heatmap (due to using blocks vs. lines). I don't plan to fix that, in most cases the half bin difference isn't enough to notice.

**Comment by dpryan79** [comment] 2018-06-07 21:30
This is now fixed in `develop`.

**Closed by dpryan79** 2018-06-07 21:30 UTC
Labels: bug
