### ISSUE TITLE
Offset shifts 1 bp than the required value

### ISSUE THREAD

**Issue by lundlab-kaltinel** [deeptools/deepTools#902] opened 2020-01-08 09:17 UTC
Hi,

I am trying to use the `Offset` option in `bamCoverage` to get specific regions of my alignments, and I am especially interested in getting the `ATG` site, therefore using offset 12 for my data provided by previous analyses.

However, it looks like `bamCoverage --offset 12 `gives me `offset 11`, as I am moving past my ATG site with `1 bp`:
![ATG-12](https://user-images.githubusercontent.com/47667755/71962906-cc749980-31fa-11ea-9fdc-68e5ae0cfc5d.png)
Is it because of `indexing` starting from `0`? ( Even though for the first base of the alignment, we need to specify it as 1).
I would be happy to have your insight, thanks!

**Comment by dpryan79** [comment] 2020-01-08 09:32
The indexing should be starting from 1, can you double check by loading the BAM file and confirming that there's really an off-by-one error (I recall checking this in IGV at the time I added `--Offset`, but perhaps I mucked something up in the code since then)?

**Comment by dpryan79** [comment] 2020-01-17 12:37
I'm using 3.3.1 locally and positive offsets are working correctly. There is an issue I just noticed with negative offsets, where instead of `-2` specifying only the next to last base, the last base ends up getting included too. I'll fix that in the next release.

Your actual issue is likely caused by the assumption that the offset should be 12 is simply wrong. Often there's a bit of variance in the correct parameter when doing things like Ribo-seq or GRO-seq and the appropriate offset needs to be changed due to random events during library prep.

**Comment by dpryan79** [comment] 2020-01-17 14:48
The negative offset issue is now fixed for the next release. Since the positive offsets seem to be working correctly I'll close this.

**Closed by dpryan79** 2020-01-17 14:48 UTC
